services:
  superset:
    image: apache/superset:latest

    ports:
      - "8088:8088"

    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py

    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
      - ../EmployeeDashboard/Database:/database
      - superset_home:/app/superset_home

    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin
      --username admin
      --firstname Tushar
      --lastname Bhatt
      --email admin@example.com
      --password admin || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "

volumes:
  superset_home: